### ISSUE TITLE
Failed install 20348

### ISSUE THREAD

**Issue by xiaozhuai** [fbactions/setup-winsdk#30] opened 2022-04-17 03:01 UTC
Response 400 Error
[https://software-download.microsoft.com/download/sg/Windows_InsiderPreview_SDK_en-us_20348_1.iso](https://software-download.microsoft.com/download/sg/Windows_InsiderPreview_SDK_en-us_20348_1.iso)

**Comment by friederbluemle** [comment] 2022-04-17 18:56
Hi @xiaozhuai - Thanks for the report. I can confirm this link does not work.
Interestingly, Wikipedia still lists 19041 as "Stable release": https://en.wikipedia.org/wiki/Microsoft_Windows_SDK

The download script used by this action contains the following note, although I don't think that matters here since 20348 was released in May 2021:
> Note: there is a delay from Windows SDK announcements to availability via the static link

Do you happen to know if there was a change in the static link format/location?

**Comment by friederbluemle** [comment] 2022-04-17 18:56
Hi @xiaozhuai - Thanks for the report. I can confirm this link does not work.
Interestingly, Wikipedia still lists 19041 as "Stable release": https://en.wikipedia.org/wiki/Microsoft_Windows_SDK

The download script used by this action contains the following note, although I don't think that matters here since 20348 was released in May 2021:
> Note: there is a delay from Windows SDK announcements to availability via the static link

Do you happen to know if there was a change in the static link format/location?

**Comment by xiaozhuai** [comment] 2022-04-18 03:45
It seems the new link format is something like this:

[https://software-download.microsoft.com/download/sg/20348.1.210507-1500.fe_release_WindowsSDK.iso](https://software-download.microsoft.com/download/sg/20348.1.210507-1500.fe_release_WindowsSDK.iso)

But I'm not sure if it will always works.

I'm still looking for a workaround to build my repo [xiaozhuai/angle_builds](https://github.com/xiaozhuai/angle_builds)

**Closed** 2023-02-06 17:15 UTC
